/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SimplifierRouteImport } from './routes/simplifier'
import { Route as EvaluatorRouteImport } from './routes/evaluator'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DailyBriefRouteImport } from './routes/daily-brief'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SimplifierRoute = SimplifierRouteImport.update({
  id: '/simplifier',
  path: '/simplifier',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluatorRoute = EvaluatorRouteImport.update({
  id: '/evaluator',
  path: '/evaluator',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyBriefRoute = DailyBriefRouteImport.update({
  id: '/daily-brief',
  path: '/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-brief': typeof DailyBriefRoute
  '/decisions': typeof DecisionsRoute
  '/evaluator': typeof EvaluatorRoute
  '/simplifier': typeof SimplifierRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-brief': typeof DailyBriefRoute
  '/decisions': typeof DecisionsRoute
  '/evaluator': typeof EvaluatorRoute
  '/simplifier': typeof SimplifierRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-brief': typeof DailyBriefRoute
  '/decisions': typeof DecisionsRoute
  '/evaluator': typeof EvaluatorRoute
  '/simplifier': typeof SimplifierRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-brief'
    | '/decisions'
    | '/evaluator'
    | '/simplifier'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-brief'
    | '/decisions'
    | '/evaluator'
    | '/simplifier'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/daily-brief'
    | '/decisions'
    | '/evaluator'
    | '/simplifier'
    | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyBriefRoute: typeof DailyBriefRoute
  DecisionsRoute: typeof DecisionsRoute
  EvaluatorRoute: typeof EvaluatorRoute
  SimplifierRoute: typeof SimplifierRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simplifier': {
      id: '/simplifier'
      path: '/simplifier'
      fullPath: '/simplifier'
      preLoaderRoute: typeof SimplifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluator': {
      id: '/evaluator'
      path: '/evaluator'
      fullPath: '/evaluator'
      preLoaderRoute: typeof EvaluatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-brief': {
      id: '/daily-brief'
      path: '/daily-brief'
      fullPath: '/daily-brief'
      preLoaderRoute: typeof DailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyBriefRoute: DailyBriefRoute,
  DecisionsRoute: DecisionsRoute,
  EvaluatorRoute: EvaluatorRoute,
  SimplifierRoute: SimplifierRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
